### ISSUE TITLE
Support modbus interface to airzone

### ISSUE THREAD

**Issue by pompompom** [Noltari/aioairzone#1]
Hi,

I have an Airzone that I have connected through modbus to my Home assistant integration. It would be interesting to use this integration through modbus( RTU & TCP) instead of though the gateway API. 

This repository has made it through this way, https://github.com/gpulido/python-airzone, however there is no Home assistant integration.

**Comment by Noltari** [comment]
> Hi,
> 
> I have an Airzone that I have connected through modbus to my Home assistant integration. It would be interesting to use this integration through modbus( RTU & TCP) instead of though the gateway API.
> 
> This repository has made it through this way, https://github.com/gpulido/python-airzone, however there is no Home assistant integration.

Hi @pompompom,

First of all excuse me for the delay.
You should know there's already an unofficial integration using python-airzone which supports modbus:
https://github.com/gpulido/homeassistant-airzone

In my opinion there should be 3 separate integrations:
1. Modbus
2. Cloud API
3. Local API

I have neither the time to develop an integration for Modbus Airzone, nor the HW, so I think that everyone with Modbus Airzone should stick to @gpulido's custom integration.

Thanks for your understanding.
