### ISSUE TITLE
Temperatura actual 0º

### ISSUE THREAD

**Issue by Fonsohome** [Noltari/aioairzone#6]
Hola, como ya dije en otro post la temperatura de la habitacion siempre marca 0º en home assistant mientras en la app airzone la marca correctamente. Los datos de diagnostico son los siguientes:

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.11.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Madrid",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.11.0",
    "host_os": "Home Assistant OS 11.1",
    "docker_version": "24.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  
  "integration_manifest": {
    "domain": "airzone",
    "name": "Airzone",
    "codeowners": [
      "@Noltari"
    ],
    "config_flow": true,
    "dhcp": [
      {
        "macaddress": "E84F25*"
      }
    ],
    "documentation": "https://www.home-assistant.io/integrations/airzone",
    "iot_class": "local_polling",
    "loggers": [
      "aioairzone"
    ],
    "requirements": [
      "aioairzone==0.6.9"
    ],
    "is_built_in": true
  },
  "data": {
    "api_data": {
      "hvac": {
        "systems": [
          {
            "data": [
              {
                "systemID": 1,
                "zoneID": 1,
                "name": "C1",
                "on": 0,
                "double_sp": 0,
                "coolsetpoint": 26.5,
                "coolmaxtemp": 30,
                "coolmintemp": 0,
                "heatsetpoint": 26.5,
                "heatmaxtemp": 30,
                "heatmintemp": 0,
                "maxTemp": 30,
                "minTemp": 0,
                "setpoint": 26.5,
                "roomTemp": 0,
                "sleep": 0,
                "temp_step": 0.5,
                "modes": [
                  2,
                  3
                ],
                "mode": 2,
                "speed_values": [
                  0
                ],
                "speeds": 0,
                "speed_type": 0,
                "speed": 0,
                "coldStages": 0,
                "coldStage": 0,
                "heatStages": 0,
                "heatStage": 0,
                "humidity": 0,
                "units": 0,
                "errors": [],
                "air_demand": 0,
                "cold_demand": 0,
                "heat_demand": 0,
                "heatangle": 0,
                "coldangle": 0
              }
            ]
          }
        ]
      },
      "webserver": {
        "mac": "**REDACTED**",
        "wifi_channel": 50,
        "wifi_quality": 0,
        "wifi_rssi": -46,
        "interface": "wifi",
        "ws_firmware": "8.3",
        "ws_type": "ws_aidoo"
      },
      "systems": {
        "systems": [
          {
            "systemID": 1,
            "mc_connected": 0,
            "system_firmware": "8.03",
            "system_type": 2,
            "manufacturer": "Unknown",
            "errors": []
          }
        ]
      },
      "dhw": {
        "data": {
          "systemID": 0,
          "acs_temp": 42,
          "acs_setpoint": 45,
          "acs_mintemp": 30,
          "acs_maxtemp": 75,
          "acs_power": 1,
          "acs_powerful": 0
        }
      },
      "version": {
        "version": "1.64A"
      }
    },
    "config_entry": {
      "entry_id": "8b25297a6ebca07b9452692b1de08095",
      "version": 1,
      "domain": "airzone",
      "title": "Airzone 192.168.1.166:3000",
      "data": {
        "host": "192.168.1.166",
        "port": 3000
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "coord_data": {
      "hot-water": {
        "name": "Airzone DHW",
        "on": true,
        "operation": 1,
        "operations": [
          0,
          1,
          2
        ],
        "temp": 42,
        "temp-max": 75,
        "temp-min": 30,
        "temp-set": 45,
        "temp-unit": 0,
        "power-mode": false
      },
      "new-systems": [],
      "num-systems": 1,
      "systems": {
        "1": {
          "available": true,
          "clamp-meter": false,
          "firmware": "8.03",
          "full-name": "Airzone [1] System",
          "id": 1,
          "manufacturer": "Unknown",
          "master-system-zone": "1:1",
          "master-zone": 1,
          "mode": 2,
          "model": "AQUAGLASS",
          "modes": [
            2,
            3,
            1
          ],
          "problems": false
        }
      },
      "webserver": {
        "firmware": "8.3",
        "full-name": "Aidoo WebServer",
        "interface": 2,
        "mac": "**REDACTED**",
        "model": "Aidoo WebServer",
        "wifi-channel": 50,
        "wifi-quality": 0,
        "wifi-rssi": -46
      },
      "new-zones": [],
      "num-zones": 1,
      "zones": {
        "1:1": {
          "absolute-temp-max": 30.0,
          "absolute-temp-min": 0.0,
          "action": 6,
          "available": true,
          "demand": false,
          "double-set-point": false,
          "id": 1,
          "master": true,
          "mode": 2,
          "name": "C1",
          "on": false,
          "problems": false,
          "system": 1,
          "temp": 0.0,
          "temp-max": 30.0,
          "temp-min": 0.0,
          "temp-unit": 0,
          "air-demand": false,
          "full-name": "Airzone [1:1] C1",
          "cool-temp-max": 30.0,
          "cool-temp-set": 26.5,
          "heat-temp-max": 30.0,
          "heat-temp-set": 26.5,
          "cold-angle": 0,
          "heat-angle": 0,
          "cold-demand": false,
          "heat-demand": false,
          "cold-stage": 0,
          "heat-stage": 0,
          "sleep": 0,
          "speed": 0,
          "speeds": [
            0
          ],
          "modes": [
            2,
            3,
            1
          ],
          "temp-set": 26.5,
          "temp-step": 0.5
        }
      },
      "version": "1.64A"
    }
  }
}

**Comment by Noltari** [comment]
> "roomTemp": 0,

Buenas @Fonsohome,

La API local de Airzone devuelve el valor 0:
`"roomTemp": 0,`
Por tanto, es un bug del FW del Aidoo Pro y no de la integración de Home Assistant / librería aioairzone-cloud, así que yo no puedo hacer nada en absoluto...

Tienes que reportarle el bug a Airzone para que saquen una actualización del FW de tu dispositivo.

Un saludo.

**Comment by Fonsohome** [comment]
Perfecto, muchas gracias.

**Comment by Noltari** [comment]
@Fonsohome voy a cerrar esta issue dado que es un bug del FW de Airzone que no podemos solventar de ninguna forma de la integración de Home Assistant.
Si al final Airzone saca una nueva actualización que lo solucione y hay algún problema puedes reabrir esta issue o crear otra nueva.

**Comment by Fonsohome** [comment]
Perdón, lo arreglaron con una actualización de FW. Se me olvidó comentarlo.
