### ISSUE TITLE
Airzone local API returning invalid min and max temperatures

### ISSUE THREAD

**Issue by scottjaffa** [Noltari/aioairzone#9]
Hi,

Thank you so much for building and maintaining this project!

I am using Daikin DKN Plus AZAI6WSPDKC firmare 4.05 and connecting through local API (not the cloud api). The data comes through fine and it can turn the units on/off and adjust mode. 
Setting temperature does not work and the HA climate card shows a range of 6-9. This looks to be a bad min and max response from the unit and doesn’t allow setting climate outside that range. While I attempt to get Daikin to fix this, would it be possible to add a validator or flag to multiply by 10, which is the correct values (operating range 60f - 90f) as shown in the Daikin app?  

Here’s the erroneous fields with a full dump below. 

coolmaxtemp
coolmintemp
heatmaxtemp
heatmintemp
maxTemp
minTemp

{
	"data":	[{
			"systemID":	1,
			"zoneID":	1,
			"name":	"Green Room",
			"on":	1,
			"coolsetpoint":	79,
			"coolmaxtemp":	9,
			"coolmintemp":	6,
			"heatsetpoint":	60,
			"heatmaxtemp":	9,
			"heatmintemp":	6,
			"maxTemp":	9,
			"minTemp":	6,
			"setpoint":	60,
			"roomTemp":	63,
			"modes":	[4, 2, 3, 5, 7],
			"mode":	3,
			"speeds":	3,
			"speed":	1,
			"coldStages":	0,
			"coldStage":	0,
			"heatStages":	0,
			"heatStage":	0,
			"humidity":	0,
			"units":	1,
			"errors":	[],
			"air_demand":	1,
			"floor_demand":	0
		}]
}

Here’s the HA error:
<img width="907" alt="image" src="https://github.com/user-attachments/assets/ffbc641f-da20-4736-a7e5-256fdd15414a">

here’s what the climate card looks like in HA:
<img width="443" alt="image" src="https://github.com/user-attachments/assets/d969cf5f-7d9f-4755-b7fa-a3359ff1ce92">

Thanks for reviewing.

**Comment by Noltari** [comment]
Thanks for the detailed report of the issue @scottjaffa.

TBH I'm tired of adding workarounds for different bugs on the Local API.

Can you contact Airzone and Daikin about the bug? There might be a FW update for your device which solves the issue.
If there's no fix then we can implement a workaround.

BTW, this might also only affect the Fahrenheit configuration. There's a high chance that the Celsius configuration isn't affected.
Therefore, you can also try to change the device config to Celsius. In the Daikin Cloud app it will be shown as Celsius, but in Home Assistant you will still see it as Fahrenheit if that's your user config.

**Comment by Noltari** [comment]
This should be fixed by https://github.com/Noltari/aioairzone/commit/d18e37ce786f0c7b8f18800bb08deb20752c4786

**Comment by scottjaffa** [comment]
Wow, thank you very much!

Yes, I am hoping Daikin will be receptive to the issue report and willing to release an update to resolve.  You are certainly much faster! 

For anyone who finds this in the future, the DKN Plus is limited, welcome to reach out to me for current information if considering getting it.

**Comment by scottjaffa** [comment]
> Can you contact Airzone and Daikin about the bug? There might be a FW update for your device which solves the issue.
> If there's no fix then we can implement a workaround.

Reopening as firmware 4.06 was released and looks to fix it if you wish to revert the change.

{
"data" : [
{
"coolsetpoint" : 75,
"heatsetpoint" : 75,
"systemID" : 1,
"setpoint" : 75,
**"heatmintemp" : 60,**
"speed_values" : [
0,
1,
2,
3
],
"speed_type" : 0,
"air_demand" : 0,
"speeds" : 3,
**"coolmintemp" : 60,**
"speed" : 0,
"modes" : [
7,
4,
2,
3,
5
],
"master_zoneID" : 1,
"double_sp" : 0,
"name" : "Laundry",
**"minTemp" : 60,**
"roomTemp" : 73,
"errors" : [

],
"humidity" : 0,
"units" : 1,
"heat_demand" : 0,
**"heatmaxtemp" : 86,
"maxTemp" : 86,**
"on" : 1,
"sleep" : 0,
"temp_step" : 2,
"mode" : 2,
**"coolmaxtemp" : 86,**
"cold_demand" : 0,
"zoneID" : 1
}
]
}
